name: tests

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  test_python_38:
    runs-on: ubuntu-latest
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: run all files
        run: |
            echo 'spawn python3 RAGnews.py\nexpect "ragnews> "\nsend "Sample input\r"\ninteract' | expect
  test_python_39:
    needs: test_python_38
    runs-on: ubuntu-latest
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: run all files
        run: |
            echo 'spawn python3 RAGnews.py\nexpect "ragnews> "\nsend "Sample input\r"\ninteract' | expect
